# Generated by Django 5.1 on 2024-08-24 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_options_alter_postmedia_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='video_link',
            new_name='video_url',
        ),
    ]
