# Generated by Django 5.1 on 2024-08-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_video_link_post_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmedia',
            options={'ordering': ['-post']},
        ),
        migrations.AddField(
            model_name='postmedia',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
