# Generated by Django 5.1 on 2024-08-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_postmedia_options_postmedia_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
