# Generated by Django 5.1 on 2024-09-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text'), ('media', 'Media'), ('url', 'Link')], default='text', max_length=10, null=True),
        ),
    ]
