# Generated by Django 5.1 on 2024-09-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text'), ('media', 'Media'), ('link', 'Link')], default='text', max_length=10, null=True),
        ),
    ]
