# Generated by Django 5.1 on 2024-10-30 11:58

import django.core.validators
import posts.models
import utils.file_utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmedia',
            options={'ordering': ['post', 'created']},
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.FileField(upload_to=posts.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'webm']), utils.file_utils.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
