# Generated by Django 5.1 on 2024-11-04 16:35

import django.core.validators
import posts.models
import utils.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_postmedia_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.FileField(upload_to=posts.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi')), utils.file_utils.validate_file_size]),
        ),
    ]
