# Generated by Django 5.1 on 2024-11-12 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_poststats'),
        ('users', '0006_alter_profile_email_alter_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poststats',
            options={'ordering': ['-created'], 'verbose_name': 'Post statistics', 'verbose_name_plural': 'Post stats'},
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
