# Generated by Django 5.1 on 2024-11-22 19:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_votepost_delete_upvotepost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poststats',
            options={'ordering': ['post'], 'verbose_name': 'Post statistics', 'verbose_name_plural': 'Post stats'},
        ),
        migrations.CreateModel(
            name='CommentStats',
            fields=[
                ('upvotes', models.PositiveIntegerField(blank=True, default=0)),
                ('downvotes', models.PositiveIntegerField(blank=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.comment')),
            ],
            options={
                'verbose_name': 'Comment statistics',
                'verbose_name_plural': 'Comment stats',
                'ordering': ['comment'],
            },
        ),
    ]
