# Generated by Django 5.1 on 2024-11-23 08:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_poststats_options_commentstats'),
        ('users', '0009_alter_profile_banner_alter_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votepost',
            options={'ordering': ['post', 'vote_type', 'created'], 'verbose_name': 'Post Vote', 'verbose_name_plural': 'Post Votes'},
        ),
        migrations.AlterField(
            model_name='commentstats',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.comment'),
        ),
        migrations.AlterField(
            model_name='votepost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
        migrations.CreateModel(
            name='VoteComment',
            fields=[
                ('vote_type', models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.comment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
            options={
                'verbose_name': 'Comment Vote',
                'verbose_name_plural': 'Comment Votes',
                'ordering': ['comment', 'vote_type', 'created'],
                'unique_together': {('comment', 'user')},
            },
        ),
    ]
