# Generated by Django 5.1 on 2024-11-02 09:05

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(default='img/banner.jpg', upload_to=users.models.upload_to),
        ),
    ]
