# Generated by Django 5.1 on 2024-11-13 08:52

import django.core.validators
import users.models
import utils.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=models.ImageField(default='default/banner.jpg', upload_to=users.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png')), utils.file_utils.validate_file_size]),
        ),
    ]
