# Generated by Django 5.1 on 2024-11-15 08:51

import django.core.validators
import users.models
import utils.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=models.ImageField(default='default/banner.jpg', upload_to=users.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp')), utils.file_utils.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default/profile_default.png', upload_to=users.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp')), utils.file_utils.validate_file_size]),
        ),
    ]
