# Generated by Django 5.1 on 2025-01-07 17:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_alter_post_user'),
        ('users', '0009_alter_profile_banner_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityStats',
            fields=[
                ('post_upvotes', models.PositiveIntegerField(default=0)),
                ('post_downvotes', models.PositiveIntegerField(default=0)),
                ('comment_upvotes', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('downvoted_comments', models.ManyToManyField(blank=True, related_name='downvoted_comments_by_user', to='posts.comment')),
                ('downvoted_posts', models.ManyToManyField(blank=True, related_name='downvoted_posts_by_user', to='posts.post')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_stats', to='users.profile')),
                ('upvoted_comments', models.ManyToManyField(blank=True, related_name='upvoted_comments_by_user', to='posts.comment')),
                ('upvoted_posts', models.ManyToManyField(blank=True, related_name='upvoted_posts_by_user', to='posts.post')),
                ('written_comments', models.ManyToManyField(blank=True, related_name='comments_by_user', to='posts.comment')),
            ],
        ),
    ]
