# Generated by Django 5.1 on 2025-01-18 13:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_useractivitystats'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon_class', models.CharField(choices=[('fa-facebook', 'Facebook'), ('fa-twitter', 'Twitter'), ('fa-instagram', 'Instagram'), ('fa-linkedin', 'LinkedIn'), ('fa-youtube', 'YouTube')], help_text='font-awesome icon class', max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='useractivitystats',
            options={'verbose_name': 'User activity stats', 'verbose_name_plural': 'User activity stats'},
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('url', models.URLField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='users.profile')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network', to='users.socialnetwork')),
            ],
        ),
    ]
