# Generated by Django 5.1 on 2024-12-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_id_alter_chat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.CharField(max_length=500),
        ),
    ]
