# Generated by Django 5.1 on 2024-12-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_body'),
        ('users', '0009_alter_profile_banner_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='online_users',
            field=models.ManyToManyField(blank=True, related_name='online_in_chat', to='users.profile'),
        ),
    ]
